version: "3"
services:
  hub:
    image: selenium/hub
    ports:
      - "4444:4444"
  chrome: 
    image: selenium/node-chrome:beta
    shm_size: '2g'
    environment:
      - SE_EVENT_BUS_HOST=hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    depends_on: 
      - hub
  firefox:
    image: selenium/node-firefox:beta
    shm_size: '1gb'
    depends_on:
      - hub
    environment:
      - SE_EVENT_BUS_HOST=hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
  bookflight:
    image: testsms/seleniumdockerdemo
    shm_size: '1g'
    environment:
      - HUB_HOST=hub
      - MODULE=testng.xml
      - BROWSER=firefox
    depends_on: 
      - chrome
      - firefox
    volumes:
      - D:\Docker Tech talk\Docker Seelnium Grid Demo\seleniumdocker\results\test-resultsbookflight:/usr/share/selenium/test-output
  bookflight1:
    image: testsms/seleniumdockerdemo
    shm_size: '1g'
    environment:
      - HUB_HOST=hub
      - MODULE=testng1.xml
    volumes:
      - D:\Docker Tech talk\Docker Seelnium Grid Demo\seleniumdocker\results\test-resultsbookflight1:/usr/share/selenium/test-output
          
